### PR TITLE
chore: typo hunting ft. codespell

### PR DESCRIPTION
**Pull request by casswedson**
I like codespell, I use it here
Adding to <https://github.com/neovim/neovim/pull/17859>

### CODE REVIEW

**Comment by zeertzjq** [comment]
I'd recommend fixing the typos in `runtime/doc/pi_netrw.txt`, `runtime/doc/syntax.txt` and `runtime/syntax/` in Vim first.

**Comment by casswedson** [comment]
Oh, is that a thing I have to do, 'cause I don't think I particularly feel like going through the trouble

**Comment by casswedson** [comment]
Now this only modifies neovim files

**Comment by dundargoc** [comment]
Oh wow, I completely missed this PR. I never look at my own fork so I missed this, my bad :). I'll take a look, thanks for the contribution.

**Comment by dundargoc** [comment]
Actually, mind just sending this to the neovim repo instead? The multiple PR thing is making me confused lol.

**Comment by zeertzjq** [comment]
I applied the diff of this PR onto <https://github.com/neovim/neovim/pull/17859>.

**Pull request closed without merging**
